name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        run: cargo clippy --workspace --all-targets --locked -- -D warnings

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo build
        run: cargo build --locked

      - name: Cargo test (workspace)
        run: cargo test --locked --workspace --all-targets

      - name: Cargo doc
        run: cargo doc --locked --no-deps

      - name: Check CLI snippets up-to-date
        run: cargo run --locked --quiet --bin gen_snippets -- --check

      - name: Native backend smoke test
        run: cargo run --locked --quiet --bin mica -- --run examples/native_entry.mica

